/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./EmptyCart.module.css";

function EmptyCart() {
  return (
    <section className={styles.emptyCart}>
      <h2 className={styles.title}>Your Cart feels empty.</h2>
      <p className={styles.description}>
        Your Shopping cart lives to serve.
        <br />
        Fill it with clothes and make it happy!
      </p>
      <button className={styles.continueButton}>Continue Shopping</button>
    </section>
  );
}

export default EmptyCart;
