/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Footer.module.css";

function Footer() {
  const socialIcons = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/708b8ee06ab9251406d9149b4bcdd0b4164860c2dfe79e34e55da49fd6c27e6b?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2",
      alt: "Facebook",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/9bf429ba5ab480fc4123ac82cf98254c6f1c6d3af0dcc722d7bbd6ff8901030a?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2",
      alt: "Twitter",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/213f392f3f3de091c2116c4731e52086e5a0e5a73817616e323100262ebcf8e3?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2",
      alt: "Instagram",
    },
  ];

  return (
    <footer className={styles.footer}>
      <div className={styles.footerContent}>
        <section className={styles.aboutSection}>
          <h3 className={styles.aboutTitle}>
            More about Ukay-Ukay Online Shope
          </h3>
          <p className={styles.aboutDescription}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim sint
            ab ullam, numquam nesciunt in.
          </p>
          <div className={styles.socialIcons}>
            {socialIcons.map((icon, index) => (
              <img
                key={index}
                loading="lazy"
                src={icon.src}
                alt={icon.alt}
                className={styles.socialIcon}
              />
            ))}
          </div>
        </section>
        <section className={styles.paymentSection}>
          <div className={styles.gcashInfo}>
            <h4 className={styles.gcashTitle}>Gcash</h4>
            <p className={styles.gcashNumber}>123456789101112</p>
          </div>
          <div className={styles.qrCode}>QR</div>
        </section>
      </div>
      <div className={styles.footerDivider} />
      <p className={styles.copyright}>
        © 2024 | Gulmatico 2nd Hand Clothing Store | All Rights Reserved |
        Powered by [YourWebDevCompanyName].com
      </p>
    </footer>
  );
}

export default Footer;
