/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.module.css";
import Logo from "../CartComponents/Logo";
import Navigation from "../CartComponents/Navigation";

const Header = () => {
  return (
    <header className={styles.header}>
      <Logo />
      <Navigation />
    </header>
  );
};


export default Header;
