/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SearchBar.module.css";

function SearchBar() {
  return (
    <form className={styles.searchBar}>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/c179f373854fce8e994bdd79b7e1fa8e2f47abce00ed2394f41876a6b479a2a2?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2"
        alt=""
        className={styles.searchIcon}
      />
      <input
        type="search"
        placeholder="Search here"
        className={styles.searchInput}
        aria-label="Search"
      />
    </form>
  );
}

export default SearchBar;
