/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import SearchBar from "./SearchBar";
import FeaturedProduct from "./FeaturedProduct";
import ProductGrid from "./ProductGrid";
import Footer from "./Footer";
import styles from "./Home.module.css";

const UkayUkayOnlineShop = () => {
  const featuredProduct = {
    name: "Product name",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo reiciendis delectus vitae, aliquid sit iure dolorum commodi eum numquam voluptate!",
    date: "16-08-24",
  };

  const products = [
    {
      name: "Name",
      price: 500.0,
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/f5283d1a5d8ba73f3cc150d8ace0f31680cdac62718466744e79541c4cfa99f9?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2",
    },
    {
      name: "Name",
      price: 500.0,
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/f5283d1a5d8ba73f3cc150d8ace0f31680cdac62718466744e79541c4cfa99f9?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2",
    },
    {
      name: "Name",
      price: 500.0,
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/f5283d1a5d8ba73f3cc150d8ace0f31680cdac62718466744e79541c4cfa99f9?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2",
    },
    {
      name: "Name",
      price: 500.0,
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/f5283d1a5d8ba73f3cc150d8ace0f31680cdac62718466744e79541c4cfa99f9?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2",
    },
    {
      name: "Name",
      price: 500.0,
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/f5283d1a5d8ba73f3cc150d8ace0f31680cdac62718466744e79541c4cfa99f9?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2",
    },
    {
      name: "Name",
      price: 500.0,
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/f5283d1a5d8ba73f3cc150d8ace0f31680cdac62718466744e79541c4cfa99f9?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2",
    },
    {
      name: "Name",
      price: 500.0,
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/f5283d1a5d8ba73f3cc150d8ace0f31680cdac62718466744e79541c4cfa99f9?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2",
    },
    {
      name: "Name",
      price: 500.0,
      imageUrl:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/f5283d1a5d8ba73f3cc150d8ace0f31680cdac62718466744e79541c4cfa99f9?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2",
    },
  ];

  return (
    <div className={styles.ukayUkayOnlineShop}>
      <Header />
      <main className={styles.mainContent}>
        <SearchBar />
        <section className={styles.limitedSection}>
          <h2 className={styles.sectionTitle}>Limited Ukay-Ukay</h2>
          <FeaturedProduct {...featuredProduct} />
        </section>
        <ProductGrid products={products} />
      </main>
      <Footer />
    </div>
  );
};

export default UkayUkayOnlineShop;
