/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Logo.module.css";

const Logo = () => {
  return (
    <img
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/c6d0a7a6f1e9238ee939c4890c892dfaf179c0c3228dd98cc1712dad2439eb75?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2"
      alt="Ukay-Ukay Online Shop Logo"
      className={styles.logo}
    />
  );
};

export default Logo;
