/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProductCard from "./ProductCard";
import styles from "./ProductGrid.module.css";

const ProductGrid = ({ products }) => {
  return (
    <section className={styles.productGrid}>
      <div className={styles.gridHeader}>
        <h2 className={styles.gridTitle}>New Arrivals</h2>
        <h2 className={styles.gridTitle}>Trending</h2>
      </div>
      <div className={styles.productsContainer}>
        {products.map((product, index) => (
          <ProductCard
            key={index}
            name={product.name}
            price={product.price}
            imageUrl={product.imageUrl}
          />
        ))}
      </div>
    </section>
  );
};

export default ProductGrid;
