/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ProfileHeader from "./ProfileHeader";
import OrderTabs from "./OrderTabs";
import ProfileSidebar from "./ProfileSidebar";
import styles from "./Profile.module.css";

const Profile = () => {
  return (
    <div className={styles.profileContainer}>
      <ProfileHeader />
      <main className={styles.mainContent}>
        <OrderTabs />
        <ProfileSidebar />
      </main>
    </div>
  );
};

export default Profile;
