/**
 * This code was generated by Builder.io.
 */
import React from "react";
import OrderTabs from "./OrderTabs";
import ProfileSidebar from "./ProfileSidebar";
import styles from "./Profile.module.css";
import Header from "./Header";
import Footer from "./Footer";

const Profile = () => {
  return (
    <div className={styles.profileContainer}>
      <Header />
      <main className={styles.mainContent}>
        <OrderTabs />
        <ProfileSidebar />
        <Footer />
      </main>
    </div>
  );
};

export default Profile;
