/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ProfileHeader.module.css";

const ProfileHeader = () => {
  return (
    <header className={styles.header}>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/c6d0a7a6f1e9238ee939c4890c892dfaf179c0c3228dd98cc1712dad2439eb75?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2"
        alt="User profile"
        className={styles.profileImage}
      />
      <nav className={styles.navigation}>
        <a href="#home" className={styles.navLink}>
          Home
        </a>
        <a href="#items" className={styles.navLink}>
          Items
        </a>
        <a href="#favorites" className={styles.navLink}>
          Favorites
        </a>
        <button className={styles.iconButton} aria-label="Notifications">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/c4ac9b1b4ea1a024a8bf70b916224f221326c5556ab6dde04bcaff22f3c50d4d?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2"
            alt=""
            className={styles.icon}
          />
        </button>
        <button className={styles.iconButton} aria-label="Messages">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/85680b86d62a6332ebc108485665dae045046ff60e38431acd4c3a845e405790?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2"
            alt=""
            className={styles.icon}
          />
        </button>
      </nav>
    </header>
  );
};

export default ProfileHeader;
