/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ProfileSidebar.module.css";

const ProfileSidebar = () => {
  const sidebarItems = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/309e1b3cf3f1177ba8594b9d10b4a3c90b9d5effde54e1abbda4f7993d04d729?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2",
      text: "My Account",
      link: "#account",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/29e38079aca54bf65045cac81316cdb26916ba3efacd35d943807bb04fe35322?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2",
      text: "My Purchase",
      link: "#purchase",
      highlight: true,
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/1592aa01444dab1b23fcad19a5536d691821640e1234b1bac18d40dd3bc03ac2?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2",
      text: "Notifications",
      link: "#notifications",
    },
  ];

  return (
    <aside className={styles.sidebar}>
      <div className={styles.searchContainer}>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/243a5ab6a60c2cb6255750ecf051eaab5a4b1f3bcd6b4623b81eb3a9a54297df?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2"
          alt=""
          className={styles.searchIcon}
        />
        <input
          type="text"
          placeholder="Search Product name here"
          className={styles.searchInput}
          aria-label="Search products"
        />
      </div>
      <nav className={styles.sidebarNav}>
        {sidebarItems.map((item, index) => (
          <a
            key={index}
            href={item.link}
            className={`${styles.sidebarLink} ${
              item.highlight ? styles.highlight : ""
            }`}
          >
            <img
              loading="lazy"
              src={item.icon}
              alt=""
              className={styles.sidebarIcon}
            />
            <span>{item.text}</span>
          </a>
        ))}
      </nav>
    </aside>
  );
};

export default ProfileSidebar;
