/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./CategorySidebar.module.css";

const categories = [
  { name: "Babies & kids", icon: "" },
  { name: "Mens", icon: "" },
  { name: "Womens", icon: "" },
];

const CategorySidebar = () => {
  return (
    <aside className={styles.sidebar}>
      <h2 className={styles.title}>Products</h2>
      <h3 className={styles.subtitle}>Shop by Category</h3>
      <ul className={styles.categoryList}>
        {categories.map((category, index) => (
          <li key={index} className={styles.categoryItem}>
            <div className={styles.categoryIcon} />
            <span className={styles.categoryName}>{category.name}</span>
          </li>
        ))}
      </ul>
    </aside>
  );
};

export default CategorySidebar;
