/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Footer.module.css";

const Footer = () => {
  return (
    <footer className={styles.footer}>
      <div className={styles.content}>
        <div className={styles.aboutSection}>
          <h4 className={styles.aboutTitle}>
            More about Ukay-Ukay Online Shop
          </h4>
          <p className={styles.aboutText}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim sint
            ab ullam, numquam nesciunt in.
          </p>
          <div className={styles.socialIcons}>
            <a href="#" aria-label="Facebook">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/71e828df22a7fdad6038c627af535ade8bce231696dd838a56f0b34849ba08e6?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2"
                alt=""
                className={styles.socialIcon}
              />
            </a>
            <a href="#" aria-label="Twitter">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/c857072da06ba33f44d251c511f35568f4952752ed3709ab7f50c9fd130906aa?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2"
                alt=""
                className={styles.socialIcon}
              />
            </a>
            <a href="#" aria-label="Instagram">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/213f392f3f3de091c2116c4731e52086e5a0e5a73817616e323100262ebcf8e3?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2"
                alt=""
                className={styles.socialIcon}
              />
            </a>
          </div>
        </div>
        <div className={styles.paymentSection}>
          <div className={styles.gcashInfo}>
            <h4 className={styles.gcashTitle}>Gcash</h4>
            <p className={styles.gcashNumber}>123456789101112</p>
          </div>
          <div className={styles.qrCode}>QR</div>
        </div>
      </div>
      <div className={styles.copyright}>
        © 2024 | Gulmatico 2nd Hand Clothing Store | All Rights Reserved |
        Powered by [YourWebDevCompanyName].com
      </div>
    </footer>
  );
};

export default Footer;
