/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.module.css";
import Logo from "../Logo/Logo";
import Navigation from "../Navigation/Navigation";
import SearchBar from "../SearchBar/SearchBar";

const Header = () => {
  return (
    <header className={styles.header}>
      <Logo />
      <Navigation />
      <SearchBar />
    </header>
  );
};

export default Header;
