/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.module.css";
import Logo from "./Logo";
import Navigation from "./Navigation";
import SearchBar from "./SearchBar";

const Header = () => {
  return (
    <header className={styles.header}>
      <Logo />
      <Navigation />
      <SearchBar />
    </header>
  );
};

export default Header;
