/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SearchBar.module.css";

const SearchBar = () => {
  return (
    <form className={styles.searchForm}>
      <label htmlFor="searchInput" className={styles.visuallyHidden}>
        Search items
      </label>
      <input
        type="search"
        id="searchInput"
        className={styles.searchInput}
        placeholder="Search here"
        aria-label="Search items"
      />
      <button type="submit" className={styles.searchButton}>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/87bd678cce24e6ded1096995259ebe7bed211ed013654e62148906c6a7ae8b22?placeholderIfAbsent=true&apiKey=63cef383af9641cc969e43f7e6acc6c2"
          alt="Search"
          className={styles.searchIcon}
        />
      </button>
    </form>
  );
};

export default SearchBar;
